# .github/workflows/deploy.yml
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # or "master" if that's your branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload /src folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: '/src'   # <<<<<<<<<< KEY: deploys your /src folder
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
