name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.14.0'  # Set your Node.js version here
    
    - name: Install dependencies
      run: |
        npm install -g sass  # Install Sass to compile SCSS
        npm install  # Install any other project dependencies (e.g., Webpack, etc.)
    
    - name: Build SCSS files
      run: |
        sass src/styles.scss dist/styles.css  # Compile your SCSS to CSS (adjust path if necessary)
     
    - name: Prepare dist directory
      run: |
        rm -rf dist  # Remove the dist directory if it exists
        mkdir dist  # Recreate the dist directory
    
    - name: Copy the required files
      run: |
        cp -r * dist/  # Copy all files to the dist folder
    
    - name: Set up Git for deployment
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Deploy to GitHub Pages
      run: |
        git clone --branch gh-pages https://github.com/Sup3rlfy/SoulflyGaming.git gh-pages
        cd gh-pages
        rm -rf *  # Clear the existing files in the gh-pages branch
        cp -r ../dist/* .  # Copy the new build files to the gh-pages branch
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages