name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # Runs on pushes to the main branch
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: write  # Allow write access to repository contents
  pages: write     # Allow write access to GitHub Pages
  id-token: write  # Allow write access to ID token for deployment

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Check if dist folder exists
        id: dist-check
        run: |
          if [ -d "dist" ]; then
            echo "Dist folder found.";
            echo "dist_exists=true" >> $GITHUB_ENV;  # Set an environment variable if dist exists
          else
            echo "Dist folder not found, building the project.";
            echo "dist_exists=false" >> $GITHUB_ENV;  # Set an environment variable if dist doesn't exist
          fi

      - name: Build the project (if dist doesn't exist)
        if: env.dist_exists == 'false'
        run: npm run build  # Replace with your specific build command

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        run: git checkout --orphan gh-pages  # Create a new orphan branch for gh-pages

      - name: Clean up working directory
        run: git rm -rf .  # Removes all files from the gh-pages branch, leaving it empty

      - name: Copy dist files from the browser folder (from existing dist folder or newly built)
        run: |
          if [ -d "dist/browser" ]; then
            echo "Found dist/browser folder. Deploying to GitHub Pages.";
            cp -r dist/browser/* .  # Copy built files from the dist/browser folder to the root of gh-pages
          else
            echo "Dist/browser folder is missing, unable to deploy.";
            exit 1;  # If dist/browser is missing, exit with error
          fi

      - name: Commit and push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy site"
          git push --force https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/Sup3rlfy/SoulflyGaming.git gh-pages