name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # Runs on pushes to the main branch

  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js with version 22.14.0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  # Updated Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build command to generate the 'dist/' folder
      - name: Build the project
        run: npm run build  # Or the appropriate build command for your project

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout gh-pages branch (creates an orphan branch if not already there)
      - name: Checkout gh-pages branch
        run: git checkout --orphan gh-pages  # This creates a new orphan branch for gh-pages

      # Copy build files to the gh-pages branch
      - name: Copy build files to gh-pages
        run: cp -r dist/* .  # Copy the contents of dist/ to the root of the gh-pages branch

      # Commit and push the changes to gh-pages
      - name: Commit and push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy site"
          git push --force https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/Sup3rlfy/SoulflyGaming.git gh-pages