name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]  # Runs on pushes to the main branch
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: write  # Allow write access to repository contents
  pages: write     # Allow write access to GitHub Pages
  id-token: write  # Allow write access to ID token for deployment

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'  # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Replace with your specific build command

      - name: Check if dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed or dist folder is missing. Skipping build step.";
            exit 1;  # Fail this step but move on to the next job
          else
            echo "Build successful, dist folder found.";
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        run: git checkout --orphan gh-pages  # Create a new orphan branch for gh-pages

      - name: Clean up working directory
        run: git rm -rf .  # Removes all files from the gh-pages branch, leaving it empty

      - name: Check if dist exists and deploy
        run: |
          if [ -d "dist" ]; then
            echo "Found dist folder. Deploying to GitHub Pages.";
            cp -r dist/* .  # Copy built files to the root of the gh-pages branch
          else
            echo "Dist folder is missing. No deployment done.";
            exit 1;  # If dist is missing, exit with error
          fi

      - name: Commit and push to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy site"
          git push --force https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/Sup3rlfy/SoulflyGaming.git gh-pages