name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.14.0'  # Set your Node.js version here
     
    - name: Install dependencies
      run: |
        npm install -g sass  # Install Sass to compile SCSS
        npm install  # Install any other project dependencies (e.g., Webpack, etc.)
    
    - name: Build SCSS files
      run: |
        sass src/styles.scss dist/styles.css  # Compile your SCSS to CSS (adjust path if necessary)
    
    - name: Prepare dist directory
      run: |
        rm -rf dist  # Remove the dist directory if it exists
        mkdir dist  # Recreate the dist directory
    
    - name: Copy the required files excluding dist directory
      run: |
        # Copy all necessary files except 'dist' into the 'dist' folder
        find . -maxdepth 1 ! -name 'dist' -exec cp -r {} dist/ \;
    
    - name: Set up Git for deployment
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Copy dist to a temporary directory
      run: |
        cp -r dist ../dist_temp  # Copy the contents of the dist folder to a temporary directory

    - name: Deploy to GitHub Pages
      run: |
        git fetch origin gh-pages || echo "No gh-pages branch found, creating one."
        git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages
        rm -rf *  # Clear the existing files in the gh-pages branch
        cp -r ../dist_temp/* .  # Copy the new build files from the temp folder to the gh-pages branch
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages  # Force push to update the gh-pages branch